require(game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game).caption("Super Ultra Mega Unfair Mode",true)
wait(2) require(game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game).caption("Very Good luck With the Chaos!",true)

-- new fog
local Lighting = game:GetService("Lighting")
Lighting.Ambient = Color3.new(255, 0, 0)
Lighting.Brightness = 0.1
Lighting.FogEnd = 50
Lighting.FogStart = 35
Lighting.FogColor = Color3.new(255, 0, 0)

-- goofy screech
game.ReplicatedStorage.Entities.Screech.Top.Eyes.Color = Color3.fromRGB(255, 0, 0)
game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game.RemoteListener.Modules.Screech.Caught.SoundId = "rbxassetid://6600188325"
game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game.RemoteListener.Modules.Screech.Caught.PlaybackSpeed = 1.6
game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game.RemoteListener.Modules.Screech.Attack.SoundId = "rbxassetid://7236490488"

-- goofy hide
game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game.RemoteListener.Modules.HideMonster.Scare.SoundId = "rbxassetid://9126213741"

-- goofy spider
game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game.RemoteListener.Modules.SpiderJumpscare.Scare.SoundId = "rbxassetid://8080941676"

-- Blindy
coroutine.wrap(function()
    while true do
        wait(90)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://pastebin.com/raw/57e7i2hg"))()
    end
end)()

-- greance 
coroutine.wrap(function()
    while true do
        wait(15)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet('https://pastebin.com/raw/WH4WDvjh'))()
    end
end)()

-- Bluyer
coroutine.wrap(function()
    while true do
        wait(90)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet('https://pastebin.com/raw/hntcsyYz'))()
    end
end)()

-- 236
coroutine.wrap(function()
    while true do
        wait(21)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet('https://pastebin.com/raw/bPYb1Kqw'))()
    end
end)()

-- 350
coroutine.wrap(function()
    while true do
        wait(20)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://pastebin.com/raw/gGkR8RMc"))()
    end
end)()

-- a-185
coroutine.wrap(function()
    while true do
        wait(25)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://pastebin.com/raw/aTy1kLpd"))()
    end
end)()

-- Cease
coroutine.wrap(function()
    while true do
        wait(32)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://pastefy.app/ofutwkjb/raw"))()
    end
end)()

-- shocker
coroutine.wrap(function()
    while true do
        wait(35)
        loadstring(game:HttpGet("https://raw.githubusercontent.com/vct0721/Doors-Stuff/refs/heads/main/Entities/Shocker"))()
    end
end)()

-- blink
coroutine.wrap(function()
    while true do
        wait(30)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
        loadstring(game:HttpGet("https://github.com/PABMAXICHAC/doors-monsters-scripts/raw/main/blinkcrux"))()
    end
end)()

-- Dread
coroutine.wrap(function()
    while true do
        wait(50)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
        loadstring(game:HttpGet("https://raw.githubusercontent.com/vct0721/Doors-Stuff/main/DreadEnity"))()
    end
end)()

-- Huntering
coroutine.wrap(function()
    while true do
        wait(20)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
        loadstring(game:HttpGet('https://pastebin.com/raw/5vLfqSWa'))()
    end
end)()

-- E-60
 
coroutine.wrap(function()
 
while true do
 
local sctm = math.random(30,15)
 
wait(sctm)
 
require(game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game).caption('Secret entity did not dangerous',true)
loadstring(game:HttpGet("https://pastebin.com/raw/Z504KNtF"))()
 
end
 
end)()

-- a-60
coroutine.wrap(function()
    while true do
        wait(60)
         game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
loadstring(game:HttpGet("https://pastebin.com/raw/KpqhHcyx"))()
 
end
 
end)()

-- Silence
coroutine.wrap(function()
    while true do
        wait(40)
         game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://pastebin.com/raw/uNnkcsGU"))()

end
    
end)()

-- hunger
coroutine.wrap(function()
    while true do
        wait(20)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://pastebin.com/raw/a9km8DA5"))()

end

end)()

-- B60
coroutine.wrap(function()
    while true do
        wait(10)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://pastebin.com/raw/2zugvBgY"))()

end

end)()

-- Bundger
coroutine.wrap(function()
    while true do
        wait(90)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://pastebin.com/raw/P1nudihg"))()

end

end)()

-- A-10
coroutine.wrap(function()
    while true do
        wait(30)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://pastebin.com/raw/PRWXYuTb"))()

end

end)()

-- Unfair Rebound 1
coroutine.wrap(function()
    while true do
        wait(70)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://pastebin.com/raw/2SAwkPLt"))()

end

end)()

-- Unfair Rebound 2
coroutine.wrap(function()
    while true do
        wait(70)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet('https://raw.githubusercontent.com/Kotyara19k-Doorsspawner/Random-files/main/ReboundHardcoreSpawn'))()

end

end)()

-- Unfair A90
coroutine.wrap(function()
    while true do
        wait(9)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://pastebin.com/raw/DsS87QeW"))()

end

end)()

-- Unfair E200
coroutine.wrap(function()
    while true do
        wait(39)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://pastebin.com/raw/BZ3gSy86"))()

end

end)()

-- Unfair A120 (Combo With E200)
coroutine.wrap(function()
    while true do
        wait(39)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://pastebin.com/raw/S9KGv5Ce"))()

end

end)()

-- Unfair Overseer Eyes
coroutine.wrap(function()
    while true do
        wait(5)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://raw.githubusercontent.com/huyhoanggphuc/Entity-obfuscate/refs/heads/main/EndlessDoors/Entity/obfuscate/Oversser.txt.lua"))()

end

end)()

-- Maniac Eyes
coroutine.wrap(function()
    while true do
        wait(31)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://raw.githubusercontent.com/huyhoanggphuc/Entity-obfuscate/refs/heads/main/Maniack%20Eyes.lua"))()

end 

end)()

-- Unfair Claim
coroutine.wrap(function()
    while true do
        wait(33)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://raw.githubusercontent.com/huyhoanggphuc/Entity-obfuscate/refs/heads/main/Claim.lua%20(1).txt"))()

end

end)()

-- Smiler
coroutine.wrap(function()
    while true do
        wait(80)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet('https://pastefy.app/YMa2CPBC/raw'))()

end

end)()
